import { chromium } from 'playwright';
const W = +(process.argv[2] || 390);
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: W, height: 844 } });
await p.goto('https://www.namlongvn.com/gioi-thieu/'); await p.waitForTimeout(3500);
await p.evaluate(() => document.querySelector('#cookie-notice')?.remove());
const dump = (sels) => p.evaluate((sels) => sels.map(s => { const e = document.querySelector(s); if (!e) return s + ' : n/a'; const c = getComputedStyle(e); const r = e.getBoundingClientRect();
  const keys = ['display','fontSize','fontFamily','lineHeight','fontWeight','color','padding','margin','borderTop','borderBottom','backgroundColor','textTransform'];
  return s + ' : box=' + [r.x, r.y, r.width, r.height].map(Math.round).join(',') + ' ' + keys.map(k => k + '=' + c[k]).filter(x => !/=(0px|none|normal|rgba\(0, 0, 0, 0\)|0px none.*)$/.test(x)).join(' ') + ((b => b.content !== 'none' ? ' ::before w=' + b.width + ' h=' + b.height + ' bg=' + b.backgroundImage.slice(0, 60) : '')(getComputedStyle(e, '::before'))); }).join('\n'), sels);
await p.click('.toggle-menu'); await p.waitForTimeout(900);
console.log('--- menu open');
console.log(await dump(['.main-menu-wrap', '.mobile-logo-container', '.navi-head', '.navi-head .lang', '.navi-head .lang a.act-l', '.navi-head .lang a:not(.act-l)', '.main-menu > li', '.main-menu > li > a', '.main-menu > li:nth-child(1) > a::after', '.bt-menu-mobile', '.bt-menu-mobile a', '.overlay-mobile']));
await p.click('.bt-menu-mobile a'); await p.waitForTimeout(900);
console.log('--- interest');
console.log(await dump(['.menu-interest', '.back-interest', '.main-m-inter', '.left-inter', '.c-interest', '#investor', '#investor .menu-mb', '#investor h3', '#investor .view-more', '#investor .l-by-inter', '#investor .l-by-inter a', '#homebuyers', '#homebuyers .menu-mb']));
await p.click('.back-interest'); await p.waitForTimeout(700);
console.log('after back: interest display=' + await p.evaluate(() => getComputedStyle(document.querySelector('.menu-interest')).display + ' menu visible=' + getComputedStyle(document.querySelector('.main-menu')).display));
await p.goto('https://www.namlongvn.com/gioi-thieu/'); await p.waitForTimeout(3000);
await p.evaluate(() => document.querySelector('#cookie-notice')?.remove());
await p.click('.toggle-menu-container .search_form'); await p.waitForTimeout(900);
console.log('--- search');
console.log(await dump(['#search', '#search .search-container', '#search .search-input', '#search .search-button', '#search .t-search', '#search .s-return li', '#search .s-return a', '.toggle-menu-container .search_form']));
await b.close();
