// Builds assets/js/search-index.js from every static page: { url, lang, title, excerpt, keywords }
// Re-run after adding/regenerating pages:  node scripts/search-index.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
const root = new URL('..', import.meta.url).pathname;
const skip = new Set(['assets', 'docs', 'node_modules', 'scripts', 'templates', 'data', '.git', '.playwright-mcp']);
const pages = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    if (skip.has(name)) continue;
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (name === 'index.html') pages.push(p);
  }
})(root);
const text = (h) => h.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/g, ' ').replace(/<[^>]+>/g, ' ')
  .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/\s+/g, ' ').trim();
const index = [];
for (const file of pages) {
  const html = readFileSync(file, 'utf8');
  const main = (html.match(/<main[\s\S]*?<\/main>/) || [''])[0];
  const url = '/' + file.slice(root.length).replace(/index\.html$/, '');
  if (url === '/' || url === '/en/homepage/') continue; // homepages are not results
  const lang = (html.match(/<html lang="([a-z]+)"/) || [, 'vi'])[1];
  const h1 = text((main.match(/<h1[\s\S]*?<\/h1>/) || [''])[0]);
  const title = h1 || text((html.match(/<title>([\s\S]*?)<\/title>/) || ['', ''])[1]).replace(/\s*[–-]\s*Nam Long Group.*$/, '');
  const paras = [...main.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map((m) => text(m[1])).filter((t) => t.length > 40);
  const excerpt = (paras[0] || '').slice(0, 220).replace(/\s\S*$/, paras[0] && paras[0].length > 220 ? ' …' : '');
  const pageTitle = text((html.match(/<title>([\s\S]*?)<\/title>/) || ['', ''])[1]).replace(/\s*[–-]\s*Nam Long Group.*$/, '');
  const keywords = pageTitle + ' · ' + [...main.matchAll(/<h[2-4][^>]*>([\s\S]*?)<\/h[2-4]>/g)].map((m) => text(m[1])).join(' · ').slice(0, 400);
  index.push({ url, lang, title, excerpt, keywords });
}
index.sort((a, b) => a.url.localeCompare(b.url));
writeFileSync(join(root, 'assets/js/search-index.js'), '/* generated by scripts/search-index.mjs */\nwindow.SEARCH_INDEX = ' + JSON.stringify(index) + ';\n');
console.log(`indexed ${index.length} pages`);
